// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBISc2sNTYTD-7-pKHm1DT5wS2wM1dGIAQ',
    appId: '1:44364675085:web:3662cad64187e9ca12bd44',
    messagingSenderId: '44364675085',
    projectId: 'mybookswap-app-b7864',
    authDomain: 'mybookswap-app-b7864.firebaseapp.com',
    storageBucket: 'mybookswap-app-b7864.firebasestorage.app',
    measurementId: 'G-TC16E3LZL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETZbpG40Yia1AM4qYoJVj4HimFZomqww',
    appId: '1:44364675085:android:b1c9ea5dbc41826412bd44',
    messagingSenderId: '44364675085',
    projectId: 'mybookswap-app-b7864',
    storageBucket: 'mybookswap-app-b7864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRX6D3vc7zKw0dCwSOCXGVwmLUSipaFwQ',
    appId: '1:44364675085:ios:46acb6d6c5e4bb3d12bd44',
    messagingSenderId: '44364675085',
    projectId: 'mybookswap-app-b7864',
    storageBucket: 'mybookswap-app-b7864.firebasestorage.app',
    iosBundleId: 'com.example.mybookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRX6D3vc7zKw0dCwSOCXGVwmLUSipaFwQ',
    appId: '1:44364675085:ios:46acb6d6c5e4bb3d12bd44',
    messagingSenderId: '44364675085',
    projectId: 'mybookswap-app-b7864',
    storageBucket: 'mybookswap-app-b7864.firebasestorage.app',
    iosBundleId: 'com.example.mybookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBISc2sNTYTD-7-pKHm1DT5wS2wM1dGIAQ',
    appId: '1:44364675085:web:a0facf29c85e53b012bd44',
    messagingSenderId: '44364675085',
    projectId: 'mybookswap-app-b7864',
    authDomain: 'mybookswap-app-b7864.firebaseapp.com',
    storageBucket: 'mybookswap-app-b7864.firebasestorage.app',
    measurementId: 'G-VYR2RC976M',
  );
}
